/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufg.es.jogovelha;

import java.awt.Container;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.Inet4Address;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.SocketException;
import java.util.ArrayList;
import java.util.List;
import java.util.Collections;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author rafae
 */
public class NewJFrame extends javax.swing.JFrame {

    private ServerSocket server;                                // Servidor
    private Socket clientSocket;                                // 
    private MinhaConexao conexao;
    private List<String> interfaces = new ArrayList<String>();
    private DefaultListModel onlineUsers;
    private ServidorJogo servidor;
    private String apelido;
    private String adversario;
    private final String peca = "X";
    private final String pecaAdversario = "O";
    private int porta;
    private int vitorias, derrotas;
    private boolean estaEscutando;
    InetAddress addr;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();

        porta = 20181;
        estaEscutando = false;
        bloqueiaTabuleiro(true);
        
        // título do programa e centraliza janela na tela
        this.setTitle("Jogo das Véia");
        this.setLocationRelativeTo(null);

        onlineUsers = new DefaultListModel();
        onlineList.setModel(onlineUsers);

        // Coleta interfaces de rede cadastradas
        try {
            Enumeration<NetworkInterface> nets = NetworkInterface.getNetworkInterfaces();
            for (NetworkInterface netint : Collections.list(nets)) {
                // descarta interfaces virtuais e loopback (127.0.0.1)
                if (netint.isVirtual() || netint.isLoopback()) {
                    continue;
                }

                // endereços associados à interface
                Enumeration<InetAddress> inetAddresses = netint.getInetAddresses();
                if (inetAddresses.hasMoreElements()) {
                    for (InetAddress inetAddress : Collections.list(inetAddresses)) {
                        if ((inetAddress instanceof Inet4Address)
                                && inetAddress.isSiteLocalAddress()) {
                            System.out.println("Adicionou uma interface");
                            interfacesComboBox.addItem(inetAddress.getHostAddress()
                                    + " - " + netint.getDisplayName());
                        }
                    }
                }
            }
        } catch (SocketException ex) {
            // aconteceu algum erro na coleta das interfaces
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        player1Label = new javax.swing.JLabel();
        player2Label = new javax.swing.JLabel();
        player2NameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jogadorVezLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        exitJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        onlineList = new javax.swing.JList<>();
        inviteFriendButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        refreshOnlineButton = new javax.swing.JButton();
        giveUpButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        interfacesComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        connectButton = new javax.swing.JButton();
        casa2Label = new javax.swing.JButton();
        casa6Label = new javax.swing.JButton();
        casa7Label = new javax.swing.JButton();
        casa1Label = new javax.swing.JButton();
        casa8Label = new javax.swing.JButton();
        casa5Label = new javax.swing.JButton();
        casa3Label = new javax.swing.JButton();
        casa4Label = new javax.swing.JButton();
        casa9Label = new javax.swing.JButton();
        vitoriasLabel = new javax.swing.JLabel();
        derrotasLabel = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        player1Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        player1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player1Label.setText("X");

        player2Label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        player2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player2Label.setText("O");

        player2NameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        player2NameLabel.setText("O outro");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Jogador da vez");

        jogadorVezLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jogadorVezLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jogadorVezLabel.setText("?");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Você");

        exitJButton.setText("Sair");
        exitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitJButtonActionPerformed(evt);
            }
        });

        onlineList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(onlineList);

        inviteFriendButton.setText("Convidar");
        inviteFriendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inviteFriendButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Jogadores Online");

        refreshOnlineButton.setText("Atualizar");
        refreshOnlineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshOnlineButtonActionPerformed(evt);
            }
        });

        giveUpButton.setText("Desistir");
        giveUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveUpButtonActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Apelido");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setText("Apelido");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Interfaces");

        connectButton.setText("Conectar");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        casa2Label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        casa2Label.setEnabled(false);
        casa2Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa2LabelActionPerformed(evt);
            }
        });

        casa6Label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        casa6Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa6LabelActionPerformed(evt);
            }
        });

        casa7Label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        casa7Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa7LabelActionPerformed(evt);
            }
        });

        casa1Label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        casa1Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa1LabelActionPerformed(evt);
            }
        });

        casa8Label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        casa8Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa8LabelActionPerformed(evt);
            }
        });

        casa5Label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        casa5Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa5LabelActionPerformed(evt);
            }
        });

        casa3Label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        casa3Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa3LabelActionPerformed(evt);
            }
        });

        casa4Label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        casa4Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa4LabelActionPerformed(evt);
            }
        });

        casa9Label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        casa9Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa9LabelActionPerformed(evt);
            }
        });

        vitoriasLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vitoriasLabel.setText("Vitórias:");

        derrotasLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        derrotasLabel.setText("Vitórias:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(vitoriasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(player1Label))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(casa1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casa4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casa7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(giveUpButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casa8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casa5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casa2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jogadorVezLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(casa6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casa3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casa9Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(player2Label)
                                .addGap(34, 34, 34))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(derrotasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(player2NameLabel)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inviteFriendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(refreshOnlineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)))
                                .addComponent(exitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(interfacesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(connectButton)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(interfacesComboBox)
                    .addComponent(connectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jLabel12)
                                .addGap(32, 32, 32)
                                .addComponent(player1Label)
                                .addGap(18, 18, 18)
                                .addComponent(vitoriasLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jogadorVezLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(casa1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(casa3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(casa2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(casa5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(casa4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(casa6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(player2NameLabel)
                                                .addGap(32, 32, 32)
                                                .addComponent(player2Label)
                                                .addGap(18, 18, 18)
                                                .addComponent(derrotasLabel)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(casa7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(casa9Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(172, 172, 172)
                                        .addComponent(casa8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(giveUpButton)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inviteFriendButton)
                            .addComponent(refreshOnlineButton)
                            .addComponent(exitJButton))
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitJButtonActionPerformed
        // encerra programa
        Container frame = exitJButton.getParent();
        do {
            frame = frame.getParent();
        } while (!(frame instanceof JFrame));

        encerraServer();

        ((JFrame) frame).dispose();
    }//GEN-LAST:event_exitJButtonActionPerformed

    private void inviteFriendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inviteFriendButtonActionPerformed
        String address = onlineList.getSelectedValue().split("-")[1];
        String message = "04";
        message += String.format("%03d", apelido.length() + 5);
        message += apelido;
        try {
            enviarMsg(message, InetAddress.getByName(address), 20181);
            adversario = onlineList.getSelectedValue();
            servidor.setEndTimeMillis(System.currentTimeMillis());
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_inviteFriendButtonActionPerformed

    private void giveUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giveUpButtonActionPerformed
        String message = "10005";
        try {
            enviarMsg(message, InetAddress.getByName(adversario.split("-")[1]), porta);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_giveUpButtonActionPerformed

    private void refreshOnlineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshOnlineButtonActionPerformed
        try {
            String mensagem = "01";
            mensagem += String.format("%03d", apelido.length() + 5);
            mensagem += apelido;
            servidor.enviarMsg(mensagem, InetAddress.getByName("255.255.255.255"), porta);
            onlineUsers.clear();
        } catch (IOException ex) {
            System.out.println("Aconteceu um erro no envio de mensagem de login");
            JOptionPane.showMessageDialog(this, "Erro no envio da mensagem de "
                    + "login", "Login", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_refreshOnlineButtonActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        if (estaEscutando) {
            try {
                server.close();
            } catch (IOException ex) {
                ex.printStackTrace();
//Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            estaEscutando = false;
            connectButton.setText("Conectar");
            jTextField1.setEnabled(true);
            interfacesComboBox.setEnabled(true);

        } else {

            int nInterface = interfacesComboBox.getSelectedIndex();
            if (nInterface < 0) {
                interfacesComboBox.requestFocus();
                return;
            }

            try {
                String str = interfacesComboBox.getItemAt(nInterface);
                String[] strParts = str.split(" - ");

                addr = InetAddress.getByName(strParts[0]);

                server = new ServerSocket(20181, 10, addr);

                estaEscutando = true;
                connectButton.setText("Desconectar");
                jTextField1.setEnabled(false);
                interfacesComboBox.setEnabled(false);
                onlineUsers.clear();
                apelido = jTextField1.getText();

                servidor = new ServidorJogo(this, server, apelido, onlineUsers, addr);
                servidor.execute();

                String mensagem = "01";
                mensagem += String.format("%03d", apelido.length() + 5);
                mensagem += apelido;

                broadcastMsg(mensagem, InetAddress.getByName("255.255.255.255"), porta);
            } catch (IOException ex) {
                //Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_connectButtonActionPerformed

    private void casa1LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa1LabelActionPerformed
        casa1Label.setText(peca);
        conexao.enviaMensagem("080061");
        bloqueiaTabuleiro(true);
    }//GEN-LAST:event_casa1LabelActionPerformed

    private void casa2LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa2LabelActionPerformed
        casa2Label.setText(peca);
        conexao.enviaMensagem("080062");
        bloqueiaTabuleiro(true);
    }//GEN-LAST:event_casa2LabelActionPerformed

    private void casa3LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa3LabelActionPerformed
        casa3Label.setText(peca);
        conexao.enviaMensagem("080063");
        bloqueiaTabuleiro(true);
    }//GEN-LAST:event_casa3LabelActionPerformed

    private void casa4LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa4LabelActionPerformed
        casa4Label.setText(peca);
        conexao.enviaMensagem("080064");
        bloqueiaTabuleiro(true);
    }//GEN-LAST:event_casa4LabelActionPerformed

    private void casa5LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa5LabelActionPerformed
        casa5Label.setText(peca);
        conexao.enviaMensagem("080065");
        bloqueiaTabuleiro(true);
    }//GEN-LAST:event_casa5LabelActionPerformed

    private void casa6LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa6LabelActionPerformed
        casa6Label.setText(peca);
        conexao.enviaMensagem("080066");
        bloqueiaTabuleiro(true);
    }//GEN-LAST:event_casa6LabelActionPerformed

    private void casa7LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa7LabelActionPerformed
        casa7Label.setText(peca);
        conexao.enviaMensagem("080067");
        bloqueiaTabuleiro(true);
    }//GEN-LAST:event_casa7LabelActionPerformed

    private void casa8LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa8LabelActionPerformed
        casa8Label.setText(peca);
        conexao.enviaMensagem("080068");
        bloqueiaTabuleiro(true);
    }//GEN-LAST:event_casa8LabelActionPerformed

    private void casa9LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa9LabelActionPerformed
        casa9Label.setText(peca);
        conexao.enviaMensagem("080069");
        bloqueiaTabuleiro(true);
    }//GEN-LAST:event_casa9LabelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    public void encerraServer() {
        try {
            // encerra conexao
            server.close();

            String mensagem = "03";
            mensagem += String.format("%03d", apelido.length() + 5);
            mensagem += apelido;
            broadcastMsg(mensagem, InetAddress.getByName("255.255.255.255"), 20181);

        } catch (IOException ex) {
            String msg = "Erro ao encerrar o server.\n" + ex.getMessage();
            JOptionPane.showMessageDialog(this, msg, "Encerrar Server",
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            // TODO envia mensagem de fechamento do programa 
        }
    }

    public void enviarMsg(String broadcastMessage, InetAddress address, int port)
            throws IOException {
        DatagramSocket socketBroadcast = null;
        socketBroadcast = new DatagramSocket(0, addr);

        DatagramPacket packet = new DatagramPacket(broadcastMessage.getBytes(), broadcastMessage.getBytes().length, address, port);
        socketBroadcast.send(packet);
    }

    public void broadcastMsg(String broadcastMessage, InetAddress address, int port)
            throws IOException {
        DatagramSocket socketBroadcast = null;
        socketBroadcast = new DatagramSocket(0, addr);
        socketBroadcast.setBroadcast(true);

        DatagramPacket packet = new DatagramPacket(broadcastMessage.getBytes(), broadcastMessage.getBytes().length, address, port);
        socketBroadcast.send(packet);
    }

    public void jogadaRecebida(int posicao) {
        switch (posicao) {
            case 1:
                casa2Label.setText(pecaAdversario);
                break;
            case 2:
                casa2Label.setText(pecaAdversario);
                break;
            case 3:
                casa3Label.setText(pecaAdversario);
                break;
            case 4:
                casa4Label.setText(pecaAdversario);
                break;
            case 5:
                casa5Label.setText(pecaAdversario);
                break;
            case 6:
                casa6Label.setText(pecaAdversario);
                break;
            case 7:
                casa7Label.setText(pecaAdversario);
                break;
            case 8:
                casa8Label.setText(pecaAdversario);
                break;
            case 9:
                casa9Label.setText(pecaAdversario);
                break;
        }
        if ((casa2Label.getText().equals(pecaAdversario) && 
                casa2Label.getText().equals(pecaAdversario) && 
                casa3Label.getText().equals(pecaAdversario)) || 
            (casa2Label.getText().equals(pecaAdversario) && 
                casa5Label.getText().equals(pecaAdversario) && 
                casa9Label.getText().equals(pecaAdversario)) || 
            (casa2Label.getText().equals(pecaAdversario) && 
                casa4Label.getText().equals(pecaAdversario) && 
                casa7Label.getText().equals(pecaAdversario)) || 
            (casa2Label.getText().equals(pecaAdversario) && 
                casa5Label.getText().equals(pecaAdversario) && 
                casa8Label.getText().equals(pecaAdversario)) || 
            (casa3Label.getText().equals(pecaAdversario) && 
                casa6Label.getText().equals(pecaAdversario) && 
                casa9Label.getText().equals(pecaAdversario)) || 
            (casa4Label.getText().equals(pecaAdversario) && 
                casa5Label.getText().equals(pecaAdversario) && 
                casa6Label.getText().equals(pecaAdversario)) || 
            (casa7Label.getText().equals(pecaAdversario) && 
                casa5Label.getText().equals(pecaAdversario) && 
                casa3Label.getText().equals(pecaAdversario)) || 
            (casa7Label.getText().equals(pecaAdversario) && 
                casa8Label.getText().equals(pecaAdversario) && 
                casa9Label.getText().equals(pecaAdversario))) {

            String mensagem9 = "09005";
            conexao.enviaMensagem(mensagem9);
            
            derrotas++;
            derrotasLabel.setText("Vitorias: " + derrotas);
            esvaziaTabuleiro();
            if(derrotas == 5){
                JOptionPane.showMessageDialog(rootPane, "Voce perdeu...");
                bloqueiaTabuleiro(true);
                conexao = null;
                derrotas = 0;
            }
        } else if (isFull()) {
            
            esvaziaTabuleiro();
            String mensagem9 = "09005";
            conexao.enviaMensagem(mensagem9);
            
        }
    }

    public void esvaziaTabuleiro(){
        casa1Label.setText(" ");
        casa2Label.setText(" ");
        casa3Label.setText(" ");
        casa4Label.setText(" ");
        casa5Label.setText(" ");
        casa6Label.setText(" ");
        casa7Label.setText(" ");
        casa8Label.setText(" ");
        casa9Label.setText(" ");
    }
    
    public void bloqueiaTabuleiro(boolean bloquear) {
        casa1Label.setEnabled(!bloquear);
        casa2Label.setEnabled(!bloquear);
        casa3Label.setEnabled(!bloquear);
        casa4Label.setEnabled(!bloquear);
        casa5Label.setEnabled(!bloquear);
        casa6Label.setEnabled(!bloquear);
        casa7Label.setEnabled(!bloquear);
        casa8Label.setEnabled(!bloquear);
        casa9Label.setEnabled(!bloquear);
    }

    public void setAdversario(String adversario) {
        this.adversario = adversario;
        this.player2NameLabel.setText(adversario);
    }

    public void setPorta(int porta) {
        this.porta = porta;
    }

    public void setConexao(MinhaConexao conexao) {
        this.conexao = conexao;
    }
    
    public void setJogadorVez(String peca){
        this.jogadorVezLabel.setText(peca);
    }
    
    public void incrementaVitoria(){
        this.vitorias++;
        this.vitoriasLabel.setText("Vitórias: " + vitorias);
        if(vitorias == 5){
            JOptionPane.showMessageDialog(rootPane, "Você ganhou!");
            bloqueiaTabuleiro(true);
            vitorias = 0;
        }
    }
    
    public boolean isFull(){
        return !casa1Label.getText().isEmpty() && 
                !casa2Label.getText().isEmpty() && 
                !casa3Label.getText().isEmpty() && 
                !casa4Label.getText().isEmpty() && 
                !casa5Label.getText().isEmpty() && 
                !casa6Label.getText().isEmpty() && 
                !casa7Label.getText().isEmpty() && 
                !casa8Label.getText().isEmpty() && 
                !casa9Label.getText().isEmpty();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton casa1Label;
    private javax.swing.JButton casa2Label;
    private javax.swing.JButton casa3Label;
    private javax.swing.JButton casa4Label;
    private javax.swing.JButton casa5Label;
    private javax.swing.JButton casa6Label;
    private javax.swing.JButton casa7Label;
    private javax.swing.JButton casa8Label;
    private javax.swing.JButton casa9Label;
    private javax.swing.JButton connectButton;
    private javax.swing.JLabel derrotasLabel;
    private javax.swing.JButton exitJButton;
    private javax.swing.JButton giveUpButton;
    private javax.swing.JComboBox<String> interfacesComboBox;
    private javax.swing.JButton inviteFriendButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jogadorVezLabel;
    private javax.swing.JList<String> onlineList;
    private javax.swing.JLabel player1Label;
    private javax.swing.JLabel player2Label;
    private javax.swing.JLabel player2NameLabel;
    private javax.swing.JButton refreshOnlineButton;
    private javax.swing.JLabel vitoriasLabel;
    // End of variables declaration//GEN-END:variables
}
